{% set name = "sphinx-autobuild" %}
{% set version = "2020.9.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4b184a7db893f2100bbd831991ae54ca89167a2b9ce68faea71eaa9e37716aed

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - sphinx-autobuild=sphinx_autobuild:main

requirements:
  host:
    - pip
    - python >=3.6
    - flit

  run:
    - python >=3.6
    - sphinx
    - livereload >=2.3.0

test:
  requires:
    - pytest
    - mock

  imports:
    - sphinx_autobuild

  commands:
    - sphinx-autobuild --help
    - pytest --pyargs sphinx_autobuild

about:
  home: https://github.com/executablebooks/sphinx-autobuild
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Watch a Sphinx directory and rebuild the documentation when a change is detected. Also includes a livereload enabled web server.


extra:
  recipe-maintainers:
    - jrderuiter
    - xhochy
