travis:
  secure:
    BINSTAR_TOKEN: izJ/9IosVtaAJKtu/r4/rEiZf4TpsMQV6ipXDZ+xFiB+18d77VrIqQ6DpQ6Fz/TOQIdIdz6yebnd60/HC14wJ3c97IidneyTzdJnBTc0xOqRHjfa9F/NhFf9GpMiUfpv4Lotgy+DKj2qRm4yIH/YD2bg/8XGtPRbmUr6bFpKzYo+w3WTTeYMKZLLaI5FbawGuxRz11KD/tItB6y0qXbNObDhV0qZHqbc1EjfDzZGNFGM8w14Vb1Z45dwz914+CZ2t6rl4tOPBM7inQLaZmXJvkeI7jvptRIlT5emFYokv+Nqqk5V8LK6XuDx2BbRlXRl55QprzrI8HhmsmOi+fi4QB/GchJUCfA8WnTo6Mpoq0/EQ7vTHZTCL3cImSaKyT6Bvp3EVu4RHe2jlvLqg5d/8kW5/52KM1ridfR4Qp/yzedJOKz3i0NInJtmvLXBnhe6yVCD6w16Gfsy0jjK9w3Nk4mG5eJNt5MWgmqbMhubYbGpNGtJA7XpYJv0C7ilyAB57ZG7JPUO7CCOc/Peo5bAL2vEPXHVukGOvR+CSbkT8QCfC+fAtzsS+sr38/mJE1bd9wv39bp5HydUt5LHbHmbatanOTvEv9YHUriWCaBdNTtC536vu0Lsfgr8dqj37Ei2qNwI1cyGraeht3m4N3OKMlua5kkFLOzhFjDB0MRLKJY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
