travis:
  secure:
    BINSTAR_TOKEN: pLuva8CQutrOOlYpzUVAsnLxw7FE1dkZ8162Ty9Jn8gC+5ktCtp6xjiNIx/RLE/3vY5UH0iyCE2MnMkYddSdtW1YNnarLSli4hfgThO2Ehkpb5yF5qvIwSl4slwDdC/S6Swq9WX0fDAp0oVaxDWXZ1WM6bDKfJfCwnO/h4PNhTXgU2arXF97ekU1D+1X2hgW4BX1uDdden4asD//A9nWOBL6IX18E+pqzR7ooDXL+4rsLi673BRh0jMZIk0jDdUSlnW3tYLF9oszhL59uVNQZETl2N2hoXOWb6U35qc3imjCyebKKDdkp4kMc/g0QXgkfV3iZbgykmKH1R1akykt1nY4275CSrcxmx+fzR5RpjnKfm2d1qMX8B3wcSy0jHIzRuTTHgBWhYjut/j+RgchZAajDKCWNJ/GXgRNM8fXoGEmMpcAyRU9IBrTdLxCLulCkP8fMfLbM9h40OPEqan3dgVU5RZVGxNPjeTQPaRz/S1aZ6nSEAHe5xa0P/GFRMmbAGSHAs/lpshzvCXT8qbdh7jdK8RFgjpIJCw721VOeCm0UDi5H5EOAbuz5gvwHy60gpBZusM5gWdi6rDJVDOAaj6KbGxJUMypFA0/PDqarcanM98/5mm1s88fN2TNZ1teWhSMhIKh7OLWk0k1lvFezLnvyguc/xkbgW55xfYIack=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
